config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    resources :campaign_finance, only: [:index] do
      post 'search', on: :collection
    end
    get '/campaign_finance/search' => 'campaign_finance#search'
  end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all
  def self.format_address(address)
    return '' unless address
    "#{address['line1'].to_s}, #{address['city'].to_s}, #{address['state'].to_s} #{address['zip'].to_s}"
  end

  def self.civic_api_to_representative_params(rep_info)
    reps = []
    if rep_info == []
      return []
    end
    
    def self.format_address(address)
      return '' unless address.is_a?(Array) && !address.empty?
      formatted_addresses = address.map do |single_address|
        line1 = single_address&.line1 || ''
        city = single_address&.city || ''
        state = single_address&.state || ''
        zip = single_address&.zip || ''
        "#{line1}, #{city}, #{state} #{zip}".strip if line1.present? || city.present? || state.present? || zip.present?
      end.compact
      formatted_addresses.join(', ')
    end

    rep_info.officials.each_with_index do |official, index|
      ocdid_temp = ''
      title_temp = ''

      rep_info.offices.each do |office|
        if office.official_indices.include? index
          title_temp = office.name
          ocdid_temp = office.division_id
        end
      end

      if !Representative.exists?(name: official.name)
        # rep = Representative.create!({ name: official.name, ocdid: ocdid_temp,
        #     title: title_temp })

        rep = Representative.create!({
          name: official.name,
          ocdid: ocdid_temp,
          title: title_temp,
          contact_address: format_address(official.address),
          political_party: official.party,
          photo_url: official.photo_url
        })
        reps.push(rep)
      end
    end

    reps
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  def show
    @representative = Representative.find(params[:id])
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                            %th Name
                            %th Office
                            %th Links
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td= rep.name
                                %td= rep.title
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles
                                    = link_to representative_path(rep.id), class: 'btn btn-info ml-2' do
                                        %i.fas.fa-user
                                        Profile

app/views/representatives/show.html.erb
<div class="container">
  <h2><%= @representative.name %></h2>
  <p>Contact Address: <%= @representative.contact_address %></p>
  <p>Political Party: <%= @representative.political_party %></p>
  <img src="<%= @representative.photo_url %>" alt="Representative Photo" width="200">
  <!-- Add other details as needed -->
  <% @representative.news_items.each do |news_item| %>
    <div class="news-item">
      <h4><%= news_item.title %></h4>
      <p><%= news_item.description %></p>
      <a href="<%= news_item.link %>" target="_blank">Read More</a>
    </div>
  <% end %>
</div>