config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    resources :campaign_finance, only: [:index] do
      post 'search', on: :collection
    end
    get '/campaign_finance/search' => 'campaign_finance#search'
  end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :county

  validates :start_time, :end_time, presence: true
  validates :start_time, date: { after_or_equal_to: proc { Time.zone.now },
                                 message:           'must be after today' }
  validates :end_time, date: { after_or_equal_to: :start_time,
                               message:           'must be after start time' }

  delegate :state, to: :county, allow_nil: true

  def county_names_by_id
    county&.state&.counties&.map { |c| [c.name, c.id] }.to_h || []
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = if params['filter-by']
                filter_events
              else
                Event.all
              end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def filter_events
    @state = State.find_by(symbol: params['state'].upcase)
    if params['filter-by'] == 'state-only'
      return Event.where(
        county: @state.counties
      )
    end

    @county = County.find_by(state_id: @state.id, fips_code: params['county'])
    Event.where(
      county: @county
    )
  end
end

app/views/events/index.html.haml
.row
    .col-12.col-md-10.offset-md-1
        %h1.text-center Events
        .clearfix.my-4
            .float-right
                .btn-group.btn-primary{ role: :group, 'aria-label': 'Events Links' }
                    = link_to events_path, class: 'btn btn-primary' do
                        %i.fas.fa-trash-restore
                        Reset Filters
                    = link_to new_my_event_path, class: 'btn btn-primary' do
                        %i.fas.fa-plus
                        Add New Event
        %hr/
        .clearfix.my-4
            .float-right
                = form_tag events_path, method: :get, class: 'form' do
                    .form-group
                        .row
                            %legend.col-form-label.col-sm-12.py-1 Filter By
                            .col-sm-12
                                .form-check
                                    = radio_button_tag 'filter-by', 'state-only', true,
                                     id: 'actionmap-events-filter-state-radio', class: 'form-check-input'
                                    %label.form-check-label{ for: 'actionmap-events-filter-state-radio' } State Only
                                .form-check
                                    = radio_button_tag 'filter-by', 'county', false,
                                     id: 'actionmap-events-filter-county-radio', class: 'form-check-input'
                                    %label.form-check-label{ for: 'actionmap-events-filter-county-radio' } County
                    .form-group.row
                        .col-12
                            = select_tag :state, options_for_select(ApplicationHelper.state_symbols_by_name),
                              { prompt: 'Select a state', class: 'form-control', id: 'actionmap-events-filter-state' }
                    .form-group.row
                        .col-12
                            = select_tag :county, options_for_select([]),
                            { prompt: 'Select a county', class: 'form-control', id: 'actionmap-events-filter-county' }
                    = submit_tag 'Filter by State', name: nil, class: 'btn btn-primary my-2',
                    id: 'actionmap-events-filter-submit', disabled: true # Enabled by Javascript
        - if @events.empty?
            .jumbotron.jumbotron-fluid.text-center
                %strong
                    There are no events that match the filters.
        .table-responsive-md
            %table.table.table-striped.table-hover#events
                %caption Table of Events
                %thead.thead-dark
                    %tr
                        %th #
                        %th Name
                        %th State
                        %th County
                        %th Start Time
                        %th End Time
                        %th Description
                        %th Link
                %tbody
                    - @events.each_with_index do |event, index|
                        %tr
                            %td= index + 1
                            %td= event.name
                            %td= event.state.name
                            %td= event.county.name
                            %td
                                %time.timeago{ datetime: event.start_time.iso8601 }
                            %td
                                %time.timeago{ datetime: event.end_time.iso8601 }
                            %td= event.description
                            %td
                                = link_to event_path(event.id), class: 'btn btn-info' do
                                    %i.fas.fa-eye
                                    View

= javascript_pack_tag 'events_index', 'data-turbolinks-track': 'reload'

app/views/events/show.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h3.text-center Event Details
        .card-body
            .card-text
                %dl.row
                    %dt.col-sm-3.text-md-right Name:
                    %dt.col-sm-9
                        = @event.name
                %dl.row
                    %dt.col-sm-3.text-md-right Description:
                    %dt.col-sm-9
                        = @event.description
                %dl.row
                    %dt.col-sm-3.text-md-right Location:
                    %dt.col-sm-9
                        "#{@event.county.name}, #{@event.state.symbol}"
                %dl.row
                    %dt.col-sm-3.text-md-right Start Time:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @event.start_time.iso8601 }
                %dl.row
                    %dt.col-sm-3.text-md-right End Time:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @event.end_time.iso8601 }
                %dl.row
                    %dt.col-sm-3.text-md-right Time Added:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @event.created_at.iso8601 }
                %dl.row
                    %dt.col-sm-3.text-md-right Last Updated:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @event.updated_at.iso8601 }
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix
            .float-right
                = link_to edit_my_event_path(@event), class: 'mx-1 btn btn-primary' do
                    %i.fas.fa-pencil
                    Edit

                = link_to events_path, class: 'mx-1 btn btn-info' do
                    %i.fas.fa-list
                    View all articles