config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    resources :campaign_finance, only: [:index] do
      post 'search', on: :collection
    end
    get '/campaign_finance/search' => 'campaign_finance#search'
  end

app/models/news_item.rb
# frozen_string_literal: true

class NewsItem < ApplicationRecord
  belongs_to :representative
  has_many :ratings, dependent: :delete_all

  def self.find_for(representative_id)
    NewsItem.find_by(
      representative_id: representative_id
    )
  end
end

app/controllers/news_items_controller.rb
# frozen_string_literal: true

class NewsItemsController < ApplicationController
  before_action :set_representative
  before_action :set_news_item, only: %i[show]

  def index
    @news_items = @representative.news_items
  end

  def show; end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end
end

app/helpers/news_item_helper.rb
# frozen_string_literal: true

module NewsItemHelper
end

app/views/news_items/index.html.haml
.container-fluid.py-5
    .row
        .col-md-8.offset-md-2
            %h1.text-center Listing News Articles for #{@representative.name}
            .clearfix.my-4
                .float-right
                    = link_to representative_new_my_news_item_path(@representative), class: 'mx-1 btn btn-primary' do
                        %i.fas.fa-plus
                        Add News Article
                    = link_to representatives_path, class: 'mx-1 btn btn-info' do
                        %i.fas.fa-list
                        All Representatives
            .table-responsive-md
                %table.table.table-striped.table-hover#events
                    %caption Table of News Items for #{@representative.name}
                    %thead.thead-dark
                        %tr
                            %th #
                            %th Name
                            %th Description
                            %th Posted
                            %th{ colspan: 3 } Links
                            %th Issues
                    %tbody
                        - @news_items.each_with_index do |item, index|
                            %tr
                                %td= index + 1
                                %td
                                    %a{ href: item.link }
                                        = item.title
                                        &nbsp;
                                        %i.fas.fa-external-link-alt
                                %td= item.description
                                %td
                                    %time.timeago{ datetime: item.created_at.iso8601 }
                                %td
                                    = link_to representative_news_item_path(item.representative.id, item.id),
                                    class: 'btn btn-info' do
                                        %i.fas.fa-eye &nbsp;Info
                                %td
                                    = link_to representative_edit_my_news_item_path(item.representative.id, item.id),
                                    class: 'btn btn-success' do
                                        %i.fas.fa-pen &nbsp;Edit
                                %td
                                    = link_to representative_news_item_path(item.representative.id, item.id),
                                    method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                                        %i.fas.fa-trash &nbsp;Delete
                                %td= item.issue

app/views/news_items/show.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h3.text-center= @news_item.title
        .card-body
            .card-text
                %dl.row
                    %dt.col-sm-3.text-md-right Link:
                    %dt.col-sm-9
                        %a{ href: @news_item.link }
                            = @news_item.link
                %dl.row
                    %dt.col-sm-3.text-md-right Description:
                    %dt.col-sm-9
                        = @news_item.description
                %dl.row
                    %dt.col-sm-3.text-md-right Representative:
                    %dt.col-sm-9
                        %a{ href: representative_path(@representative) }
                            = @news_item.representative.name
                %dl.row
                    %dt.col-sm-3.text-md-right Time Added:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @news_item.created_at.iso8601 }
                %dl.row
                    %dt.col-sm-3.text-md-right Last Updated:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @news_item.updated_at.iso8601 }
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix
            .float-right
                = link_to representative_edit_my_news_item_path(@representative, @news_item),
                 class: 'mx-1 btn btn-primary' do
                    %i.fas.fa-pencil
                    Edit

                = link_to representative_news_items_path(@representative),
                 class: 'mx-1 btn btn-info' do
                    %i.fas.fa-list
                    View all articles