config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    resources :campaign_finance, only: [:index] do
      post 'search', on: :collection
    end
    get '/campaign_finance/search' => 'campaign_finance#search'
  end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Add more Authentication Providers here.
  enum provider: { google_oauth2: 1, github: 2 }, _prefix: :provider

  # Each (uid, provider) pair should be unique.
  validates :uid, uniqueness: { scope: :provider }

  def name
    "#{first_name} #{last_name}"
  end

  def auth_provider
    {
      'google_oauth2' => 'Google',
      'github'        => 'Github'
    }[provider]
  end

  def self.find_google_user(uid)
    User.find_by(
      provider: User.providers[:google_oauth2],
      uid:      uid
    )
  end

  def self.find_github_user(uid)
    User.find_by(
      provider: User.providers[:github],
      uid:      uid
    )
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < SessionController
  def profile
    @user = User.find_by(id: session[:current_user_id])

    if @user.nil?
      flash[:alert] = 'User not found. Please log in.'
      redirect_to login_path
    end
    # Other profile action logic here...
  end
end

app/views/user/profile.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h3.text-center Your Profile
        .card-body
            .card-text
                %dl.row
                    %dt.col-sm-3.text-md-right Name:
                    %dt.col-sm-9
                        = @user.name
                %dl.row
                    %dt.col-sm-3.text-md-right Authentication Provider:
                    %dt.col-sm-9
                        = @user.auth_provider
                %dl.row
                    %dt.col-sm-3.text-md-right Email:
                    %dt.col-sm-9
                        = @user.email
                %dl.row
                    %dt.col-sm-3.text-md-right Created:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @user.created_at.iso8601 }
                %dl.row
                    %dt.col-sm-3.text-md-right Last Updated:
                    %dt.col-sm-9
                        %time.timeago{ datetime: @user.updated_at.iso8601 }
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix
            .float-right
                = link_to logout_path, class: 'mx-1 btn btn-info' do
                    %i.fas.fa-sign-out-alt
                    Logout